language: node_js
node_js:
  - "5.1"
before_install:
  -  gem install sass
  -  npm cache -f clean
  -  npm install -g ionic@beta
  -  npm install -g cordova
install: npm install
before_script: ionic build
