language: node_js
node_js:
  - "0.10"
before_install:
  -  gem install sass
  -  npm cache -f clean
  -  npm install -g ionic@beta
  -  npm install -g cordova
  -  npm install -g protractor
  -  npm install -g karma
  -  export DISPLAY=:99.0
  -  sh -e /etc/init.d/xvfb start
install: npm install
before_script: gulp build
